### ISSUE TITLE
Clay tool uncraftable? F3 limited since updating v3 to v7.. intentional?

### ISSUE THREAD

**Issue by csisDustin** [Samlegamer/rlcraft-reimagined-1.16.5#13]
I can still get coords other ways, but biomes?  the F3 help menu is limited, shows chunks
![2022-02-18_11 40 14](https://user-images.githubusercontent.com/76239814/154743517-31a68f4d-47f3-407c-873f-8ebb91b250ac.png)

advancement "Ceramics" not available with clay_tool uncraftable. /give [me] notreepunching:clay_tool works for this, but if it's disabled for some reason? 

restarting from scratch in v 1.7 I broke over 100 leaves to get 4 sticks, releasing more than 8 ent/tree mobs. but once I had an axe, I've now got over abundance of sticks every time a fell a tree. weird imbalance.

btw: I do luv this game, but still confused with some of the tech..

**Comment by Samlegamer** [comment]
I was convinced that the Clay Tools were disabled in the original RLCraft, but obviously not.
The coordinates were disabled in v6 to match the original, to get the coordinates in the new versions you need a compass.
And for the leaves it's quite weird, because I increased the drop rate of the stick with a datapack.

**Comment by csisDustin** [comment]
you might be right about clay tools disabled for balancing?, it's been a
while since I played rlcraft, I just thought it's weird to have a mod and
not use it.. but I see it's only a small part of a large mod..
Yes, the coord are disabled during many server games, I get that.. thanks
for the compass info. Is there a biome compass? plus killing enders to make
tp portals really helped. as does waystones.
Again with the weird part, you increased drop rate, and I see that when
felling trees, but I hardly get any when breaking just leaves. can you/I
increase the drops per leaf-block??

**Comment by csisDustin** [comment]
I seem clay obsessed? sorry

**Comment by Samlegamer** [comment]
fixed in 1.8
