### ISSUE TITLE
Patch Note 1.8 !

### ISSUE THREAD

**Issue by Samlegamer** [Samlegamer/rlcraft-reimagined-1.16.5#14]
Add Better Animals Plus (for Deer and Turkey) !
Add Multi Mine (thanks atomicstryker) !
Add Betternether Reforged !
Add Spartan Weaponry: Ice and Fire !
Add Tons Of Enchants (for Enchantments)
Add Dusk Mod (for Difficulty)

More Dungeons :
Add Awesome Dungeon End !
Add Awesome Dungeon Nether !
Add Awesome Dungeon Ocean !

Concerns felt, the experience was slow is very little.
These mods add more experience on the spawners:
Add NotEnoughExperience
Add Simple XP Config

Fix Health Bar (Mantle)
Fix Clay Tools Recipes
Fix Golden Armors Furnace
Fix [HIGH] Wolf armors infinite !
Fix Summoning Mob Effect (https://www.reddit.com/r/feedthebeast/comments/r3gt36/how_to_make_it_so_that_lycanites_tames_and/)
Fix Dragon Spawn (After Ice Spawning in Taiga 😑) and other Fire Dragon Spawn :)

New Modded Eating Animation !
Recipes Changes !

Remove Modifier Mod !
Add Quality Equipment Mod (Quality Tools)
Convert Quality Tools config to Quality Equipment !

**Comment by 2327063537** [comment]
When will the 1.8 version be updated?pls

**Comment by Samlegamer** [comment]
it will be out soon, I don't have a fixed date

**Comment by deadphyre** [comment]
I know it's only been a month but was wondering what the status on the 1.8 release is?

**Comment by Samlegamer** [comment]
I'm trying to fix as many things as possible, and I'm waiting for an Ice and Fire update to fix some bugs.

**Comment by deadphyre** [comment]
> I'm trying to fix as many things as possible, and I'm waiting for an Ice and Fire update to fix some bugs.

What bugs are present in the May 21st release of Ice and Fire? Maybe I could help track down a fix?

**Comment by Okminji** [comment]
Ummm, is the new version releasing anytime soon? It has been quite a while

**Comment by Samlegamer** [comment]
> 

https://github.com/AlexModGuy/Ice_and_Fire/issues/4635

**Comment by Samlegamer** [comment]
Hello, I have solved the main problems that prevent the update for 1 years, it should be released soon.

**Comment by Samlegamer** [comment]
Uploaded
