### ISSUE TITLE
Why is stick drop rates lower than the Og RLCraft?

### ISSUE THREAD

**Issue by Ninjabros156** [Samlegamer/rlcraft-reimagined-1.16.5#3]
when I attempt a hardcore run, I feel like the leaves on trees almost never drop their sticks but Ents instead, is this on purpose? 
If so, let me know!

**Comment by Samlegamer** [comment]
Unfortunately this is something that is no longer configurable.
Until I create a datapack to patch this, break the tree branches by hand.

**Comment by Ninjabros156** [comment]
ok thanks for the info!
